name: Complete Pilates
favicon: null
layout_spectrum: 0.8559459066018462
typography_spectrum: 0.8502301257103682
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3037141766399145
  lightness: 0.9470241374801844
  saturation: 0.008255981607362628
  rhythmicContrast: 0.10776529996655881
purpose: []
