name: Complete Pilates
favicon: null
layout_spectrum: 0.10595
typography_spectrum: 0.26869
title: 'A weekly pilates class in Central Manchester, every Tuesday night at 8pm. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#066e71'
    - '#ffffff'
    - '#c5a953'
    - '#46888c'
    - '#cbddde'
  brandStrength: 0.5625
  lightness: 1
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
